apiVersion: v1
kind: Service
metadata:
  name: rp-ngoma-college-website
spec:
  selector:
    app: rp-ngoma-college-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer